#requires -Version 5.1
<#
.SYNOPSIS
    Build-time wrapper for Invoke-AgentHandler.ps1: regenerates the job scripts and
    writes a sqlcmd :r manifest of them.

.DESCRIPTION
    Runs Invoke-AgentHandler.ps1 to regenerate the per-job T-SQL under OutputPath, then
    writes <OutputPath>/<ManifestName> -- a small manifest of sqlcmd :r directives, one
    per generated job script.

    This is for database projects (SSDT, or an SDK-style .sqlproj) that deploy jobs
    from their post-deploy script. The post-deploy holds a single stable line that
    :r-includes the manifest, so adding or removing a job under SourcePath needs no
    post-deploy edit: the manifest is regenerated on every build and always matches
    whatever the generator produced.

    Fails (throws) if any job folder fails to generate, and does so before rewriting the
    manifest, so a broken job can't silently drop out of the deploy.

.PARAMETER SourcePath
    Folder of job definitions, one subfolder per job. Defaults to job-source/ next to
    this script.

.PARAMETER OutputPath
    Folder the generated job scripts and the manifest are written to. Defaults to
    job-tsql/ next to this script.

.PARAMETER ManifestName
    File name of the manifest written into OutputPath. Defaults to _include.sql.

.PARAMETER HelperDatabase
    Passed through to Invoke-AgentHandler.ps1. Omit it to use the generator's default.

.EXAMPLE
    .\Build-AgentJobs.ps1 -SourcePath .\agent-jobs\job-source -OutputPath .\agent-jobs\job-tsql
#>
[CmdletBinding()]
param(
    [string] $SourcePath,
    [string] $OutputPath,
    [string] $ManifestName = '_include.sql',
    [string] $HelperDatabase
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Resolve paths relative to this script so the caller's working directory doesn't matter.
# $PSScriptRoot can be empty in some hosts; fall back sensibly.
$scriptDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptDir)) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }

if ([string]::IsNullOrWhiteSpace($SourcePath)) { $SourcePath = Join-Path $scriptDir 'job-source' }
if ([string]::IsNullOrWhiteSpace($OutputPath)) { $OutputPath = Join-Path $scriptDir 'job-tsql' }

$generator = Join-Path $scriptDir 'Invoke-AgentHandler.ps1'
if (-not (Test-Path -LiteralPath $generator)) {
    throw "Generator not found at '$generator'. Build-AgentJobs.ps1 must sit next to Invoke-AgentHandler.ps1."
}

# 1) Regenerate every job under SourcePath into OutputPath.
$generatorArgs = @{ SourcePath = $SourcePath; OutputPath = $OutputPath }
if ($PSBoundParameters.ContainsKey('HelperDatabase')) { $generatorArgs.HelperDatabase = $HelperDatabase }

# Seeded to 0 first, because the generator only sets $LASTEXITCODE when it *fails*: on a
# clean run it returns without calling exit, leaving the variable unset -- and under
# Set-StrictMode reading an unset automatic variable is itself a terminating error.
$LASTEXITCODE = 0
& $generator @generatorArgs

# The generator exits non-zero when a job folder fails to build, and `& script.ps1` does NOT
# propagate that -- exit inside a called script ends that script, not this one. Without this
# check a broken job folder builds "successfully": step 2 rewrites the manifest from whatever
# DID generate, so the broken job silently vanishes from the deploy. Throw so the build
# fails, and do it before writing a manifest that would look clean.
if ($LASTEXITCODE -ne 0) {
    throw "Invoke-AgentHandler failed (exit $LASTEXITCODE). Manifest not rewritten -- fix the job source and rebuild."
}

# 2) Rewrite the manifest from whatever the generator just produced.
#    One :r per job script, paths relative to the manifest's own folder, which is how
#    sqlcmd and DacFx resolve nested :r includes. Sorted for deterministic diffs.
$manifestFile = Join-Path $OutputPath $ManifestName
$jobScripts = @(Get-ChildItem -LiteralPath $OutputPath -File -Filter '*.sql' |
    Where-Object { $_.Name -ne $ManifestName } |
    Sort-Object Name)

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine('-- MACHINE-GENERATED by Build-AgentJobs.ps1 -- DO NOT EDIT.')
$null = $sb.AppendLine('-- Manifest of generated SQL Agent job scripts, for :r inclusion from a post-deploy script.')
$null = $sb.AppendLine()
if ($jobScripts.Count -eq 0) {
    $null = $sb.AppendLine("PRINT 'Invoke-AgentHandler: no agent-job scripts to deploy.';")
}
else {
    foreach ($f in $jobScripts) {
        # sqlcmd :r wants a Windows-style relative path; quote it for spaces/parens in job names.
        $null = $sb.AppendLine(":r `".\$($f.Name)`"")
    }
}

# UTF-8 without BOM, matching the generator's output for clean diffs and sqlcmd.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($manifestFile, $sb.ToString(), $utf8NoBom)

Write-Host "Build-AgentJobs: wrote manifest '$manifestFile' listing $($jobScripts.Count) job script(s)."
